### ISSUE TITLE
LQIP error

### ISSUE THREAD

**Issue by HunselM** [aceforth/nuxt-optimized-images#170]
**Describe the bug**
The LQIP loader seems to get stuck, while using Nuxt Development mode.
I'm getting the following error: **Error: Input file is missing or of an unsupported image format lqip v2.1.0.** After about 14% of the build process I'm getting stuck.

Installed versions:
- Nuxt 2.12.0
- @bazzite/nuxt-optimized-images 0.4.0
- lqip-loader 2.1.0

**To Reproduce**

1. install dependencies
2. yarn dev

**Screenshots**
![Schermafbeelding 2020-04-09 om 23 05 07](https://user-images.githubusercontent.com/7252657/78940695-92938780-7ab6-11ea-8125-768023639b21.png)

**Comment by juliomrqz** [comment]
@HunselM, `lqip` doesn't support all kind of images https://github.com/zouhir/lqip/blob/master/index.js#L11
