### ISSUE TITLE
All images inside `/assets` getting inlined

### ISSUE THREAD

**Issue by joehand** [aceforth/nuxt-optimized-images#186]
**Describe the bug**

All of the images inside the assets folder are getting inlined, even over the limit (causing app.js to be large!). I also tried to set `inlineImageLimit: -1` and still had all images inlined.

I also tried with version `0.4.0` with same result.

**To Reproduce**
1. Site available at https://github.com/codeforscience/codeforscience.org/tree/better-images
2. Run `nuxt build --analyze`

**Expected behavior**
Inline config to be respected and images over limit not be inlined.

**Screenshots**

This build has  `inlineImageLimit: -1` . 

![image](https://user-images.githubusercontent.com/684965/81761554-0ee70500-947f-11ea-944f-6fcda918674a.png)

**Desktop (please complete the following information):**
- Node v12, npm v6.14.5
- Build tried on several computers + netlify with same result

**Comment by joehand** [comment]
A few updates (still no fix):

* I confirmed that the option is properly getting set here:

```js
  {
    loader: 'url-loader',
    options: getUrlLoaderOptions(moduleConfig)
  }
```

```js
// console.log(options) => 
 {
  name: 'img/[contenthash:7].[ext]',
  limit: -1,
  fallback: 'file-loader'
}
```

However, does not seem to not being reflected in the webpack config.


* I was able to add the config to `nuxt.config.js` and it did not inline images

```js
config.module.rules.push(
          {
            test: /\.(png|jp(e*)g|svg)$/,
            use: [{
                loader: 'url-loader',
                options: {
                    limit: -1, // Convert images < 8kb to base64 strings
                    name: 'img/[contenthash:7].[ext]'
               }
            }]
          }
        )
```

**Comment by vonec** [comment]
optimizedImages: {
      optimizeImages: true,
      inlineImageLimit: -1
    },

-1 might be a issue plz check

**Comment by joehand** [comment]
Okay, figured it out! I was using dynamic requires, which results in ALL images being added. One of those was inlined:

```
<img :src="require(`@/assets${this.$store.state.globals.logo}?inline`)" />
```

... which resulted in everything under `@assets` to be inlined.
